name: PushGameToWebsite

#~~~~~~WHEN~~~~~~~~~
on:
  push:
    paths:
      - 'recent_web_build/my_rustlike_bg.wasm'
      - 'recent_web_build/my_rustlike.js'
    
  workflow_dispatch:

#~~~~WHAT TO DO~~~~~~
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Push a file to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: recent_web_build/
          destination-repository-name: 'Portfolio'
          user-email: benji6090@gmail.com
          destination-github-username: 'benlloyd50'
          commit-message: New build for roguelike pushed
